# Generated by Django 6.0.5 on 2026-05-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_order_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='passenger_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='ticket',
            name='passenger_name',
            field=models.CharField(blank=True, max_length=110),
        ),
    ]
