# Generated by Django 6.0.5 on 2026-05-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0005_ticket_passenger_email_ticket_passenger_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airplane',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='airplanetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='crew',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name_plural': 'Crew'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['source', 'destination']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['flight', 'row', 'seat']},
        ),
    ]
